services:
  - type: web
    name: wizard-table-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CLIENT_URL
        sync: false
